FROM mcr.microsoft.com/devcontainers/base:noble
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y graphviz cmake dpkg-dev build-essential debhelper devscripts dh-make gnupg dput fakeroot